site_name: PyCAMPS

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - markdown_include.include:
      base_path: docs
  - toc:
      permalink: true
      toc_depth: 3

nav:
  - Home: index.md
  - Installation: installation.md
  - API Reference: api_reference.md
  - Examples:
    - Basic Usage: examples/pycamps_intro.ipynb

plugins:
  - search
  - mkdocs-jupyter
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_source: false
            show_root_heading: true
            show_category_heading: false
            show_docstring_examples: false
            heading_level: 3